<a href="https://colab.research.google.com/github/Krzesimir13/Udemy_DS/blob/main/221_230_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Science Bootcamp

### Spis treści:
* [Import biblioteki](#0)
* [Ćwiczenie 221](#1)
* [Ćwiczenie 222](#2)
* [Ćwiczenie 223](#3)
* [Ćwiczenie 224](#4)
* [Ćwiczenie 225](#5)
* [Ćwiczenie 226](#6)
* [Ćwiczenie 227](#7)
* [Ćwiczenie 228](#8)
* [Ćwiczenie 229](#9)
* [Ćwiczenie 230](#10)

### <a name='0'></a>Import biblioteki

In [1]:
import numpy as np
np.random.seed(20)

np.__version__

'2.0.2'

### <a name='a11'></a> Rozwiązywanie układów równań
Rozważmy układ równań $U$:  
$${\displaystyle \mathrm {U} \colon {\begin{cases}{\begin{matrix}a_{11}x_{1}&+&a_{12}x_{2}&+&\dots &+&a_{1n}x_{n}&=b_{1},\\a_{21}x_{1}&+&a_{22}x_{2}&+&\dots &+&a_{2n}x_{n}&=b_{2},\\\vdots &&\vdots &&\ddots &&\vdots &\vdots \\a_{m1}x_{1}&+&a_{m2}x_{2}&+&\dots &+&a_{mn}x_{n}&=b_{m}.\end{matrix}}\end{cases}}.}$$

Wykorzystując macierze możemy to przedstawić następująco:

$${\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}{\begin{bmatrix}x_{1}\\x_{2}\\\vdots \\x_{n}\end{bmatrix}}={\begin{bmatrix}b_{1}\\b_{2}\\\vdots \\b_{m}\end{bmatrix}}$$
I w zapisie skrótowym:
$$\mathbf {AX} =\mathbf {B}$$

Gdzie:  
$A = {\begin{bmatrix}a_{11}&a_{12}&\dots &a_{1n}\\a_{21}&a_{22}&\dots &a_{2n}\\\vdots &\vdots &\ddots &\vdots \\a_{m1}&a_{m2}&\dots &a_{mn}\end{bmatrix}}$ - macierz współczynników

${\displaystyle \mathbf {B} =[b_{1},b_{2},\dots ,b_{m}]} $ - wektor wyrazów wolnych  
${\mathbf  X}=[x_{1},x_{2},\dots ,x_{n}] $ - wektor niewiadomych

Jeśli macierz układu $A$ jest macierzą kwadratową, to oznaczoność układu jest równoważna jej odwracalności, tzn.
$$\mathbf {AX} =\mathbf {B}$$
$${\displaystyle \mathbf {A} ^{-1}\mathbf {AX} =\mathbf {A} ^{-1}\mathbf {B}} $$
$$\mathbf {X} =\mathbf {A} ^{-1}\mathbf {B} .$$

#### Przykład:
Rozważmy układ równań:
$$\begin{cases}2x + 4y = 10 \\ x - y = -1 \end{cases}$$  
Rozwiązaniem jest para liczb:
$$\begin{cases}x = 1 \\ y = 2 \end{cases}$$  


### <a name='1'></a> Ćwiczenie 221
Wykorzystując bibliotekę numpy rozwiąż poniższy układ równań:

$$\begin{cases}5x - 3y = 21 \\ x - 2y = 7 \end{cases}$$

In [63]:
A = np.array([[5, -3], [1, -2]])
B = np.array([[21], [7]])

X = np.dot(np.linalg.inv(A), B)
X

array([[ 3.],
       [-2.]])

Dokonaj sprawdzenia.

__Wskazówka:__ Użyj funkcji _np.allclose()_.

In [64]:
sol1 = np.linalg.solve(A, B)

np.allclose(X, sol1)

True

### <a name='2'></a> Ćwiczenie 222
Wykorzystując bibliotekę numpy rozwiąż poniższy układ równań:

$$\begin{cases}x + y + z = 1 \\ 2x + y + 5z = 0 \\ x - y = z \end{cases}$$

In [65]:
C = [[1, 1, 1], [2, 1, 5], [1, -1, -1]]
D = [[1], [0], [0]]

X2 = np.dot(np.linalg.inv(C), D)
X2

array([[ 0.5  ],
       [ 0.875],
       [-0.375]])

Dokonaj sprawdzenia.

__Wskazówka:__ Użyj funkcji _np.allclose()_.

In [66]:
sol2 = np.linalg.solve(C, D)

np.allclose(X2, sol2)

True

### <a name='3'></a> Ćwiczenie 223
Załaduj popularny zbiór danych IRIS do zmiennej _data_raw_ wykorzystując bibliotekę _scikit-learn_.

In [6]:
from sklearn.datasets import load_iris

raw_data = load_iris()
iris = raw_data.copy()

Wyświetl opis zbioru IRIS

In [7]:
iris['DESCR']

'.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 150 (50 in each of three classes)\n:Number of Attributes: 4 numeric, predictive attributes and the class\n:Attribute Information:\n    - sepal length in cm\n    - sepal width in cm\n    - petal length in cm\n    - petal width in cm\n    - class:\n            - Iris-Setosa\n            - Iris-Versicolour\n            - Iris-Virginica\n\n:Summary Statistics:\n\n============== ==== ==== ======= ===== ====================\n                Min  Max   Mean    SD   Class Correlation\n============== ==== ==== ======= ===== ====================\nsepal length:   4.3  7.9   5.84   0.83    0.7826\nsepal width:    2.0  4.4   3.05   0.43   -0.4194\npetal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\npetal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n============== ==== ==== ======= ===== ====================\n\n:Missing Attribute Values: None\n:Class Distribution: 

Wyświetl nazwy zmiennych w zbiorze.

In [8]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [16]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

Wyświetl nazwy klas w zbiorze.

In [17]:
iris['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

### <a name='4'></a> Ćwiczenie 224
Do zmiennej _data_ przypisz dane (tablica numpy) zbioru IRIS.

In [18]:
data = iris['data']

Do zmiennej _target_ przypisz wartości zmiennej docelowej ze zbioru IRIS.

In [19]:
target = iris['target']

Zbadaj kształt zmiennej _data_ oraz _target_.

In [20]:
print('Data:', data.shape)
print('Target:', target.shape)

Data: (150, 4)
Target: (150,)


### <a name='5'></a> Ćwiczenie 225
Podziel dane na zbiór treningowy (_data_train_, _target_train_) i testowy (_data_test_, _target_test_). Rozmiar zbioru testowego to 30% próbek.

In [34]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.3)

Wyświetl rozmiar zbiorów:
* _data_train_
* _target_train_
* _data_test_
* _target_test_

In [35]:
print('X_train:', X_train.shape)
print('Y_train:', y_train.shape)
print('X_test:', X_test.shape)
print('Y_test:', y_test.shape)

X_train: (105, 4)
Y_train: (105,)
X_test: (45, 4)
Y_test: (45,)


### <a name='6'></a> Ćwiczenie 226
Zbuduj model regresji logistcznej (ustaw domyślne wartości parametrów) wykorzystując bibliotekę scikit-learn oraz dane IRIS.

In [23]:
from sklearn.linear_model import LogisticRegression

regr = LogisticRegression()

Dopasuj dane treningowe do modelu.

In [27]:
regr.fit(data, target)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

### <a name='7'></a> Ćwiczenie 227
Dokonaj oceny modelu na zbiorze treningowym.

In [57]:
regr.score(X_train, y_train)

0.9809523809523809

Dokonaj oceny modelu na zbiorze testowym.

In [58]:
regr.score(X_test, y_test)

0.9555555555555556

### <a name='8'></a> Ćwiczenie 228
Dokonaj predykcji na danych testowych na podstawie modelu i przypisz je do zmiennej _target\_pred_.

In [48]:
target_pred = regr.predict(X_test)

Wyświetl zmienną _target\_pred_.

In [50]:
target_pred

array([0, 2, 1, 1, 0, 0, 2, 1, 0, 1, 2, 0, 2, 1, 2, 0, 1, 1, 2, 0, 2, 1,
       1, 2, 2, 1, 1, 1, 0, 2, 0, 2, 0, 2, 1, 1, 0, 0, 1, 1, 0, 2, 2, 0,
       1])

Wyświetl zmienną _target\_test_.

In [49]:
y_test

array([0, 2, 1, 1, 0, 0, 2, 1, 0, 1, 2, 0, 2, 1, 2, 0, 1, 1, 2, 0, 2, 1,
       1, 1, 2, 1, 1, 1, 0, 2, 0, 2, 0, 1, 1, 1, 0, 0, 1, 1, 0, 2, 2, 0,
       1])

### <a name='9'></a> Ćwiczenie 229
Wyznacz macierz pomyłek (macierz konfuzji)

In [61]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  2],
       [ 0,  0, 12]])

### <a name='10'></a> Ćwiczenie 230
Wyświetl raport klasyfikacji modelu.

In [54]:
from sklearn.metrics import classification_report

print(classification_report(y_test, target_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      0.89      0.94        19
           2       0.86      1.00      0.92        12

    accuracy                           0.96        45
   macro avg       0.95      0.96      0.96        45
weighted avg       0.96      0.96      0.96        45

